frr version 8.4_git
frr defaults traditional
hostname leaf2
no ipv6 forwarding
!
interface eth1
 ip address 10.10.18.5/30
exit
!
interface lo
 ip address 10.255.0.2/32
exit
!
router bgp 65102
 bgp router-id 10.255.0.2
 neighbor 10.10.18.6 remote-as 65000
 neighbor 10.255.0.1 remote-as 65101
 neighbor 10.255.0.1 ebgp-multihop 2
 neighbor 10.255.0.1 disable-connected-check
 neighbor 10.255.0.1 update-source 10.255.0.2
 !
 address-family ipv4 unicast
  network 10.255.0.2/32
  neighbor 10.10.18.6 route-map PERMIT-ALL in
  neighbor 10.10.18.6 route-map PERMIT-ALL out
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 10.255.0.1 activate
  neighbor 10.255.0.1 route-map PERMIT-ALL in
  neighbor 10.255.0.1 route-map PERMIT-ALL out
  advertise-all-vni
  vni 10100
   route-target import 65000:10100
   route-target export 65000:10100
  exit-vni
 exit-address-family
exit
!
route-map PERMIT-ALL permit 10
exit
!
